-- # 40 SQL Practice Questions – SH Schema

-- ## SELECT + WHERE
-- 1. From `SH.CUSTOMERS`, display customer ID, first name, last name, gender, and marital status for all female customers.
-- SELECT CUST_ID,CUST_FIRST_NAME,CUST_LAST_NAME,CUST_GENDER,CUST_MARITAL_STATUS FROM sh.CUSTOMERS WHERE CUST_GENDER='F';

-- 2. From `SH.CUSTOMERS`, find customers whose last name starts with `S` and whose year of birth is greater than 1970.
-- SELECT * FROM SH.CUSTOMERS WHERE CUST_LAST_NAME LIKE 'S%' AND CUST_YEAR_OF_BIRTH > 1970;

-- 3. From `SH.PRODUCTS`, display product ID, product name, category, and list price for products whose list price is between 100 and 500.
-- SELECT PROD_ID,PROD_NAME,PROD_CATEGORY,PROD_LIST_PRICE FROM SH.PRODUCTS WHERE PROD_LIST_PRICE BETWEEN 100 AND 500;

-- 4. From `SH.PRODUCTS`, find products whose minimum price is less than 50 and whose status is `available`.
-- SELECT PROD_ID,PROD_NAME,PROD_MIN_PRICE FROM SH.PRODUCTS WHERE PROD_MIN_PRICE<50 AND PROD_STATUS IS NOT NULL;
-- SELECT PROD_ID,PROD_NAME,PROD_MIN_PRICE FROM SH.PRODUCTS WHERE PROD_MIN_PRICE<50 AND PROD_STATUS ='AVAILABLE';

-- 5. From `SH.SALES`, display product ID, customer ID, quantity sold, and amount sold for transactions where the amount sold is greater than 1000.
-- SELECT PROD_ID,CUST_ID,QUANTITY_SOLD,AMOUNT_SOLD FROM SH.SALES WHERE AMOUNT_SOLD>1000;

-- 6. From SH.SALES, find transactions where the quantity sold is greater than 2 and the channel ID is 3.
-- SELECT * FROM SH.SALES WHERE QUANTITY_SOLD > 2 AND CHANNEL_ID = 3;

-- 7. From SH.CHANNELS, display channel ID and channel description for channels whose description contains the word Direct.
-- SELECT CHANNEL_ID, CHANNEL_DESC FROM SH.CHANNELS WHERE CHANNEL_DESC LIKE '%Direct%';

-- 8. From SH.PROMOTIONS, display promotion ID, promotion name, cost, and category where promotion cost is greater than 1000.
-- SELECT PROMO_ID, PROMO_NAME, PROMO_COST, PROMO_CATEGORY FROM SH.PROMOTIONS WHERE PROMO_COST > 1000;

-- 9. From SH.PROMOTIONS, find promotions whose end date is greater than their begin date and whose promotion cost is greater than 500.
-- SELECT * FROM SH.PROMOTIONS WHERE PROMO_END_DATE > PROMO_BEGIN_DATE AND PROMO_COST > 500;

-- 10. From SH.COUNTRIES, display country ID, country name, and region ID for countries belonging to region ID 52790.
-- SELECT COUNTRY_ID, COUNTRY_NAME, COUNTRY_REGION_ID FROM SH.COUNTRIES WHERE COUNTRY_REGION_ID = 52790;

-- 11. From SH.TIMES, display time ID, day name, calendar month name, and calendar year for dates belonging to the year 2000.
-- SELECT TIME_ID, DAY_NAME, CALENDAR_MONTH_NAME, CALENDAR_YEAR FROM SH.TIMES WHERE CALENDAR_YEAR = 2000;

-- 12. From SH.TIMES, find all dates where the calendar month name is December and the calendar year is 2001.
-- SELECT TIME_ID FROM SH.TIMES WHERE CALENDAR_MONTH_NAME = 'December' AND CALENDAR_YEAR = 2001;

-- 13. From SH.COSTS, display product ID, time ID, unit cost, and unit price where unit price is greater than unit cost.
-- SELECT PROD_ID, TIME_ID, UNIT_COST, UNIT_PRICE FROM SH.COSTS WHERE UNIT_PRICE > UNIT_COST;

-- 14. From SH.COSTS, find records where unit cost is greater than 100 and unit price is less than 1000.
-- SELECT * FROM SH.COSTS WHERE UNIT_COST > 100 AND UNIT_PRICE < 1000;

-- 15. From SH.SUPPLEMENTARY_DEMOGRAPHICS, display customer ID, education, occupation, and household size for customers whose household size is greater than 3.
-- SELECT CUST_ID, EDUCATION, OCCUPATION, HOUSEHOLD_SIZE FROM SH.SUPPLEMENTARY_DEMOGRAPHICS WHERE HOUSEHOLD_SIZE IN ('4-5','6-8','9+');-- select * from sh.SALES;

-- ## GROUP BY – DIFFERENT BUSINESS QUESTIONS


-- 16. Number of customers belonging to each marital status
-- SELECT CUST_MARITAL_STATUS, COUNT(*) AS CUSTOMER_COUNT FROM SH.CUSTOMERS GROUP BY CUST_MARITAL_STATUS;

-- 17. Average customer year of birth for each gender
-- SELECT CUST_GENDER, AVG(CUST_YEAR_OF_BIRTH) AS AVG_YEAR_OF_BIRTH FROM SH.CUSTOMERS GROUP BY CUST_GENDER;

-- 18. Average list price of products in each product category
-- SELECT PROD_CATEGORY, AVG(PROD_LIST_PRICE) AS AVG_LIST_PRICE FROM SH.PRODUCTS GROUP BY PROD_CATEGORY;

-- 19. Highest minimum price in each product subcategory
-- SELECT PROD_SUBCATEGORY, MAX(PROD_MIN_PRICE) AS Highest_MIN_PRICE FROM SH.PRODUCTS GROUP BY PROD_SUBCATEGORY;

-- 20. Total sales amount generated by each channel
-- SELECT CHANNEL_ID, SUM(AMOUNT_SOLD) AS TOTAL_SALES FROM SH.SALES GROUP BY CHANNEL_ID;

-- 21. Total quantity sold for each product
-- SELECT PROD_ID, SUM(QUANTITY_SOLD) AS TOTAL_QUANTITY_SOLD FROM SH.SALES GROUP BY PROD_ID;

-- 22. Average sales amount for each promotion
-- SELECT PROMO_ID, AVG(AMOUNT_SOLD) AS AVG_SALES_AMOUNT FROM SH.SALES GROUP BY PROMO_ID;

-- 23. Total promotion cost for each promotion category
-- SELECT PROMO_CATEGORY, SUM(PROMO_COST) AS TOTAL_PROMOTION_COST FROM SH.PROMOTIONS GROUP BY PROMO_CATEGORY;

-- 24. Number of countries belonging to each region
-- SELECT COUNTRY_REGION_ID, COUNT(*) AS COUNTRY_COUNT FROM SH.COUNTRIES GROUP BY COUNTRY_REGION_ID;

-- 25. Average unit cost for each product
-- SELECT PROD_ID, AVG(UNIT_COST) AS AVG_UNIT_COST FROM SH.COSTS GROUP BY PROD_ID;

-- ## TWO-LEVEL GROUP BY

-- 26. Count customers by gender and marital status
-- SELECT CUST_GENDER, CUST_MARITAL_STATUS, COUNT(*) AS CUSTOMER_COUNT FROM SH.CUSTOMERS GROUP BY CUST_GENDER, CUST_MARITAL_STATUS;

-- 27. Count products by product category and product subcategory
-- SELECT PROD_CATEGORY, PROD_SUBCATEGORY, COUNT(*) AS PRODUCT_COUNT FROM SH.PRODUCTS GROUP BY PROD_CATEGORY, PROD_SUBCATEGORY;

-- 28. Calculate total sales amount for each product and channel combination
-- SELECT PROD_ID, CHANNEL_ID, SUM(AMOUNT_SOLD) AS TOTAL_SALES FROM SH.SALES GROUP BY PROD_ID, CHANNEL_ID;

-- 29. Calculate total quantity sold for each channel and promotion combination
-- SELECT CHANNEL_ID, PROMO_ID, SUM(QUANTITY_SOLD) AS TOTAL_QUANTITY_SOLD FROM SH.SALES GROUP BY CHANNEL_ID, PROMO_ID;

-- 30. Find the average unit cost for each product and promotion combination
-- SELECT PROD_ID, PROMO_ID, AVG(UNIT_COST) AS AVG_UNIT_COST FROM SH.COSTS GROUP BY PROD_ID, PROMO_ID;

-- ## WHERE + GROUP BY

-- 31. Total sales amount for each channel where AMOUNT_SOLD > 500
-- SELECT CHANNEL_ID, SUM(AMOUNT_SOLD) AS TOTAL_SALES FROM SH.SALES WHERE AMOUNT_SOLD > 500 GROUP BY CHANNEL_ID;

-- 32. Average list price for each product category where list price > 100
-- SELECT PROD_CATEGORY, AVG(PROD_LIST_PRICE) AS AVG_LIST_PRICE FROM SH.PRODUCTS WHERE PROD_LIST_PRICE > 100 GROUP BY PROD_CATEGORY;

-- 33. Count customers by marital status for customers born after 1970
-- SELECT CUST_MARITAL_STATUS, COUNT(*) AS CUSTOMER_COUNT FROM SH.CUSTOMERS WHERE CUST_YEAR_OF_BIRTH > 1970 GROUP BY CUST_MARITAL_STATUS;

-- 34. Average promotion cost for each promotion category where cost > 500
-- SELECT PROMO_CATEGORY, AVG(PROMO_COST) AS AVG_PROMOTION_COST FROM SH.PROMOTIONS WHERE PROMO_COST > 500 GROUP BY PROMO_CATEGORY;

-- 35. Maximum unit price for each product where unit cost > 50
-- SELECT PROD_ID, MAX(UNIT_PRICE) AS MAX_UNIT_PRICE FROM SH.COSTS WHERE UNIT_COST > 50 GROUP BY PROD_ID;

-- 36. Marital statuses having more than 100 customers
-- SELECT CUST_MARITAL_STATUS, COUNT(*) AS CUSTOMER_COUNT FROM SH.CUSTOMERS GROUP BY CUST_MARITAL_STATUS HAVING COUNT(*) > 100;

-- 37. Product categories whose average list price is greater than 500
-- SELECT PROD_CATEGORY, AVG(PROD_LIST_PRICE) AS AVG_LIST_PRICE FROM SH.PRODUCTS GROUP BY PROD_CATEGORY HAVING AVG(PROD_LIST_PRICE) > 500;

-- 38. Channels whose total sales amount is greater than 100000
-- SELECT CHANNEL_ID, SUM(AMOUNT_SOLD) AS TOTAL_SALES FROM SH.SALES GROUP BY CHANNEL_ID HAVING SUM(AMOUNT_SOLD) > 100000;

-- 39. Promotion categories whose average promotion cost is greater than 1000
-- SELECT PROMO_CATEGORY, AVG(PROMO_COST) AS AVG_PROMOTION_COST FROM SH.PROMOTIONS GROUP BY PROMO_CATEGORY HAVING AVG(PROMO_COST) > 1000;

-- 40. Products whose average unit price is greater than 500
-- SELECT PROD_ID, AVG(UNIT_PRICE) AS AVG_UNIT_PRICE FROM SH.COSTS GROUP BY PROD_ID HAVING AVG(UNIT_PRICE) > 500;
